/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import java.text.DecimalFormat;

/**
 *
 * @author Lirio
 */
public class Problema04 extends javax.swing.JFrame {
    static Problema04 app;
     
    /**
     * Creates new form Problema04
     */
    public Problema04() {
        initComponents();
        label2.setVisible(false);
        textfield2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        title = new javax.swing.JLabel();
        labelChooseFigure = new javax.swing.JLabel();
        comboBoxChooseFigure = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        buttonCalcularArea = new javax.swing.JButton();
        buttonCalcularCircunferencia = new javax.swing.JButton();
        textfield1 = new javax.swing.JTextField();
        textfield2 = new javax.swing.JTextField();
        labelArea = new javax.swing.JLabel();
        labelCincurferencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 0));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Figuras geométricas");

        labelChooseFigure.setForeground(new java.awt.Color(255, 255, 255));
        labelChooseFigure.setText("Escolha um figura");

        comboBoxChooseFigure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Círculo", "Triângulo", "Quadrado", "Retângulo" }));
        comboBoxChooseFigure.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxChooseFigureItemStateChanged(evt);
            }
        });
        comboBoxChooseFigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxChooseFigureActionPerformed(evt);
            }
        });

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Raio");

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Altura");

        buttonCalcularArea.setText("Calcular área");
        buttonCalcularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularAreaActionPerformed(evt);
            }
        });

        buttonCalcularCircunferencia.setText("Calcular circunferência");
        buttonCalcularCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularCircunferenciaActionPerformed(evt);
            }
        });

        textfield1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        textfield2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield2ActionPerformed(evt);
            }
        });

        labelArea.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelArea.setForeground(new java.awt.Color(255, 255, 255));
        labelArea.setText("0.0");

        labelCincurferencia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelCincurferencia.setForeground(new java.awt.Color(255, 255, 255));
        labelCincurferencia.setText("0.0");

        jDesktopPane1.setLayer(title, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelChooseFigure, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(comboBoxChooseFigure, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(label1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(label2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonCalcularArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonCalcularCircunferencia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textfield1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textfield2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelCincurferencia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(labelCincurferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelArea)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelChooseFigure)
                                .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(label2))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(title)
                                .addComponent(comboBoxChooseFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(buttonCalcularCircunferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCalcularArea)))
                .addGap(30, 30, 30))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(title)
                .addGap(36, 36, 36)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChooseFigure)
                    .addComponent(comboBoxChooseFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCalcularArea, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonCalcularCircunferencia, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCincurferencia)
                    .addComponent(labelArea))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularAreaActionPerformed
        // TODO add your handling code here:
        if(textfield1.getText().isEmpty()) return;
        
        String item = comboBoxChooseFigure.getSelectedItem().toString();
        final var twoDecimal = new DecimalFormat("0.00");
        
        switch (item) {
            case "Círculo" -> {
                final var radius = Float.valueOf(textfield1.getText());
                final var circle = new Circulo(radius, "");
                final var area = twoDecimal.format(circle.area());
                labelArea.setText(area);
            }
            case "Triângulo" -> {
                if(textfield2.getText().isEmpty()) return;
                
                final var base = Float.valueOf(textfield1.getText());
                final var height = Float.valueOf(textfield2.getText());
                final var triangle = new Triângulo(base, height, "");
                final var area = twoDecimal.format(triangle.area());
                labelArea.setText(area);
            }
            case "Quadrado" -> {
                final var side = Float.valueOf(textfield1.getText());
                final var square = new Quadrado(side, "");
                final var area = twoDecimal.format(square.area());
                labelArea.setText(area);
            }
            case "Retângulo" -> {
                if(textfield2.getText().isEmpty()) return;
                
                final var base = Float.valueOf(textfield1.getText());
                final var height = Float.valueOf(textfield2.getText());
                final var rectangle = new Retangulo(base, height, "");
                final var area = twoDecimal.format(rectangle.area());
                labelArea.setText(area);
            }
            default -> {
            }
        }
        //throw new AssertionError();
    }//GEN-LAST:event_buttonCalcularAreaActionPerformed

    private void buttonCalcularCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularCircunferenciaActionPerformed
        // TODO add your handling code here:
        if(textfield1.getText().isEmpty()) return;
        
        final var twoDecimal = new DecimalFormat("0.00");

        final var radius = Float.valueOf(textfield1.getText());
        final var circle = new Circulo(radius, "");
        final var circunference = twoDecimal.format(circle.getCircunference());
        labelCincurferencia.setText(circunference);
    }//GEN-LAST:event_buttonCalcularCircunferenciaActionPerformed

    private void textfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield2ActionPerformed

    private void comboBoxChooseFigureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxChooseFigureItemStateChanged
        // TODO add your handling code here:
        String item = comboBoxChooseFigure.getSelectedItem().toString();
        
        //Limpar o valor das caixas de texto
        textfield1.setText("");
        textfield2.setText("");
        labelArea.setText("");
        labelCincurferencia.setText("");

        //Se for círculo mostra o botão para calcular circunferência
        if (item.equals("Círculo")) {
            label1.setText("Raio");
            label2.setVisible(false);
            textfield2.setVisible(false);
            textfield2.setText("");

            buttonCalcularCircunferencia.setVisible(true);
            labelCincurferencia.setVisible(true);
        } else {
            buttonCalcularCircunferencia.setVisible(false);
            labelCincurferencia.setVisible(false);
        }

        switch (item) {
            case "Triângulo" -> {
                label1.setText("Base");
                label2.setText("Altura");
                label2.setVisible(true);
                
                textfield2.setVisible(true);
            }
            case "Quadrado" -> {
                label1.setText("Lado");
                label2.setVisible(false);
                
                textfield2.setVisible(false);
            }
            case "Retângulo" -> {
                label1.setText("Base");
                label2.setVisible(true);
                label2.setText("Altura");
                
                textfield2.setVisible(true);
            }
            default -> {
            }
        }
        //throw new AssertionError();
    }//GEN-LAST:event_comboBoxChooseFigureItemStateChanged

    private void comboBoxChooseFigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxChooseFigureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxChooseFigureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                app = new Problema04();
                app.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcularArea;
    private javax.swing.JButton buttonCalcularCircunferencia;
    private javax.swing.JComboBox<String> comboBoxChooseFigure;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labelArea;
    private javax.swing.JLabel labelChooseFigure;
    private javax.swing.JLabel labelCincurferencia;
    private javax.swing.JTextField textfield1;
    private javax.swing.JTextField textfield2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
