/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;

/**
 *
 * @author Lirio
 */
public class Problema05 extends javax.swing.JFrame {
    static Problema05 app;

    private final ArrayList<Book> myBooks = new ArrayList<>();
    private final ArrayList<String> myTitles = new ArrayList<>();
    private boolean listDataIsEmpty = true;

    private String[] bookToArrayData(Book book) {
        String[] bookData = {
            "Título: " + book.getTitle(),
            "Autor: " + book.getAuthor(),
            "Editora: " + book.getPublisher(),
            "Edição: " + book.getEdition(),
            "Ano: " + book.getYear(),
            "Páginas: " + book.getPages(),};

        return bookData;
    }
    
    private void errorStatus(String message) {
        jLabelStatus.setForeground(Color.RED);
        jLabelStatus.setText(message);
    }

    /**
     * Creates new form Problema05
     */
    public Problema05() {
        initComponents();
        jButtonBookDetails.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMyBooks = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jLabelPublisher = new javax.swing.JLabel();
        jLabelPages = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldYear = new javax.swing.JTextField();
        jTextFieldAuthor = new javax.swing.JTextField();
        jTextFieldPublisher = new javax.swing.JTextField();
        jTextFieldPages = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonShowBooks = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMyBooks = new javax.swing.JList<>();
        jLabelUpperTitle1 = new javax.swing.JLabel();
        jButtonBookDetails = new javax.swing.JButton();
        jTextFieldEdition = new javax.swing.JTextField();
        jLabelEdition = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMyBooks.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelMyBooks.setText("MEUS LIVROS");

        jLabelTitle.setText("Título");

        jLabelAuthor.setText("Autor");

        jLabelYear.setText("Ano");

        jLabelPublisher.setText("Editora");

        jLabelPages.setText("Páginas");

        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });

        jTextFieldYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYearActionPerformed(evt);
            }
        });

        jTextFieldAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAuthorActionPerformed(evt);
            }
        });

        jTextFieldPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPublisherActionPerformed(evt);
            }
        });

        jTextFieldPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPagesActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Adicionar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonShowBooks.setText("Listar");
        jButtonShowBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowBooksActionPerformed(evt);
            }
        });

        jListMyBooks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Clique em listar para ver os seus livros" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListMyBooks.setVerifyInputWhenFocusTarget(false);
        jListMyBooks.setVisibleRowCount(5);
        jScrollPane1.setViewportView(jListMyBooks);

        jLabelUpperTitle1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabelUpperTitle1.setText("PREENCHA O FORMULÁRIO PARA ADICIONAR UM NOVO LIVRO");

        jButtonBookDetails.setText("Detalhes");
        jButtonBookDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookDetailsActionPerformed(evt);
            }
        });

        jLabelEdition.setText("Edição");

        jLabelStatus.setText("Status: Tente adicionar um novo livro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMyBooks)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUpperTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelPublisher)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabelTitle))
                                        .addComponent(jLabelAuthor)
                                        .addComponent(jLabelYear)
                                        .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelPages)
                                        .addComponent(jTextFieldPages, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelEdition)))
                                .addComponent(jTextFieldPublisher)
                                .addComponent(jTextFieldAuthor)
                                .addComponent(jTextFieldTitle)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonShowBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBookDetails)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelMyBooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUpperTitle1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTitle)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAuthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPublisher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelYear)
                            .addComponent(jLabelPages)
                            .addComponent(jLabelEdition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdd))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jButtonShowBooks)
                    .addComponent(jButtonBookDetails))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void jTextFieldYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYearActionPerformed

    private void jTextFieldAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAuthorActionPerformed

    private void jTextFieldPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPublisherActionPerformed

    private void jTextFieldPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPagesActionPerformed

    private void jButtonShowBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowBooksActionPerformed
        // TODO add your handling code here:
        if (listDataIsEmpty) {
            String[] listEmptyMessage = {"Hum... a sua lista está vazia!"};
            jListMyBooks.setListData(listEmptyMessage);
            return;
        }

        //CONVERTER LISTA DE TÍTULOS PARA VETOR DE STRING
        String[] listData
                = Arrays.copyOf(myTitles.toArray(), myTitles.size(), String[].class
                );
        jListMyBooks.setListData(listData);

        jButtonShowBooks.setEnabled(false);
        jButtonBookDetails.setEnabled(true);
    }//GEN-LAST:event_jButtonShowBooksActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // VERIFICAR SE TODOS ESSES CAMPOS ESTÃO PREENCHIDOS
        boolean titleIsEmpty = jTextFieldTitle.getText().isEmpty();
        boolean authorIsEmpty = jTextFieldAuthor.getText().isEmpty();
        boolean publisherIsEmpty = jTextFieldPublisher.getText().isEmpty();

        if (titleIsEmpty || authorIsEmpty || publisherIsEmpty) {
            return;
        }

        int edition, year, pages;

        //TRATAR EXCEÇÃO QUANDO O USUÁRIO DIGITAR ALGO DIFERENTE DE NÚMERO
        try {
            year = Integer.parseInt(jTextFieldYear.getText());
            pages = Integer.parseInt(jTextFieldPages.getText());
            edition = Integer.parseInt(jTextFieldEdition.getText());
        } catch (NumberFormatException e) {
            errorStatus("Ano, páginas ou edição inválido");
            return;
        }
        
        Calendar today = Calendar.getInstance();
        
        //VERIFIDCAR SE O ANO ESTÁ ENTRE 1500 E HOJE
        if (year < 1500 || year > today.get(Calendar.YEAR)) {
            errorStatus("Ano inválido!");
            return;
        } else if(pages < 1){
            errorStatus("Número de páginas inválido!");
            return;
        } else if(edition < 1) {
            errorStatus("Edição inválido!");
            return;
        }

        String title, author, publisher;

        title = String.valueOf(jTextFieldTitle.getText());
        author = String.valueOf(jTextFieldAuthor.getText());
        publisher = String.valueOf(jTextFieldPublisher.getText());

        final var newBook = new Book(title, author, edition, year, publisher, pages);
        myBooks.add(newBook);
        myTitles.add(title);

        //LIMPAR TODOS OS CAMPOS DE TEXTO
        jTextFieldTitle.setText("");
        jTextFieldAuthor.setText("");
        jTextFieldPublisher.setText("");
        jTextFieldPages.setText("");
        jTextFieldYear.setText("");
        jTextFieldEdition.setText("");

        jLabelStatus.setForeground(Color.blue);
        jLabelStatus.setText("Livro adicionado com sucesso!");
        listDataIsEmpty = false;
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonBookDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookDetailsActionPerformed
        // TODO add your handling code here:
        int index = jListMyBooks.getSelectedIndex();
        if (index < 0) {
            errorStatus("Selecione um livro primeiro!");
            return;
        }

        jLabelStatus.setForeground(Color.BLACK);
        jLabelStatus.setText("Status: Zzz!");
        Book book = myBooks.get(index);

        String[] bookData = bookToArrayData(book);
        jListMyBooks.setListData(bookData);

        jButtonShowBooks.setEnabled(true);
        jButtonBookDetails.setEnabled(false);
    }//GEN-LAST:event_jButtonBookDetailsActionPerformed

    /**
     * //
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema05.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema05.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema05.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema05.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                app = new Problema05();
                app.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBookDetails;
    private javax.swing.JButton jButtonShowBooks;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelEdition;
    private javax.swing.JLabel jLabelMyBooks;
    private javax.swing.JLabel jLabelPages;
    private javax.swing.JLabel jLabelPublisher;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUpperTitle1;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JList<String> jListMyBooks;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldEdition;
    private javax.swing.JTextField jTextFieldPages;
    private javax.swing.JTextField jTextFieldPublisher;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
